// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "";
const ENABLED = Boolean(SUPABASE_URL) && Boolean(SUPABASE_PUBLISHABLE_KEY);

const createStub = () => {
  const makeBuilder = () => {
    const response = { data: [] as unknown[], error: null as null };
    const b = {
      select: (_q?: string) => b,
      eq: (_col?: string, _val?: unknown) => b,
      order: (_col?: string, _opts?: { ascending?: boolean }) => b,
      update: async () => ({ error: null as null }),
      delete: async () => ({ error: null as null }),
      insert: async () => ({ error: null as null }),
      single: async () => ({ data: null as unknown, error: null as null }),
      then: (resolve: (arg: { data: unknown[]; error: null }) => unknown) => resolve(response),
      catch: (_reject?: unknown) => {},
    };
    return b;
  };
  return {
    auth: {
      onAuthStateChange: (_cb: unknown) => ({
        data: { subscription: { unsubscribe: () => {} } },
      }),
      getSession: async () => ({ data: { session: null as unknown } }),
      signInWithPassword: async () => ({ error: { message: "Auth disabled (no Supabase)" } }),
      signUp: async () => ({ error: { message: "Auth disabled (no Supabase)" } }),
      signOut: async () => {},
    },
    from: (_table: string) => makeBuilder(),
  } as unknown as ReturnType<typeof createClient<Database>>;
};

export const supabase = ENABLED
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createStub();
